Kelompok1/urls.py
from django.contrib import admin
from django.urls import path, include
from crowdfunding.views import daftar

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homePage.urls')),
    path('crowd/', include(('crowdfunding.urls', 'crowdfunding'), namespace = "crowdfunding")),
    path('viewmore/', include('viewmore.urls')),
    path('history/', include('history.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

crowdfunding/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views
from .views import *
from django.conf import settings

urlpatterns = [
	path('daftar', daftar, name = 'daftar'),
	path('logout', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name = 'logout'),
	path('donasi', donasi, name = 'donasi'),
	path('terdonasi', savedatadonasi, name = 'terdonasi'),
    # url(r'^logout/$', views.logout, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
	path('data_dict/', data_func, name="data_func")
]

history/urls.py
from django.urls import path
from history import views

urlpatterns = [
    path('', views.history_func,  name="history"),
]

crowdfunding/models.py
from django.db import models
from django.utils import timezone
from datetime import date
# Create your models here.
class Model_Daftar(models.Model):
	nama = models.CharField(max_length=200)
	tanggal_lahir = models.DateField(max_length=200)
	email = models.EmailField(unique = True)
	password = models.CharField(max_length = 200)
	

class Model_Donasi(models.Model):
	nama_program = models.CharField(max_length=200)
	nama = models.CharField(max_length = 200)
	email = models.EmailField()
	jumlah = models.IntegerField()

# ============== azhar's code ==================
class User_Data(models.Model):
 	user_id = models.IntegerField()
 	user_program = models.CharField(max_length=200)
 	user_money = models.IntegerField()
# ============== azhar's code ==================
	
def __str__(self):
	return self.nama

crowdfunding/forms.py
from django import forms
import datetime
from viewmore.models import Program


class Form_Daftar(forms.Form):

    error_messages = {
        'required': 'Please type',
    }

    nama_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Lengkap',
        'class' : 'form-control',
    }

    tanggal_lahir_attrs = {
        'type': 'date',
        'placeholder' : 'Tanggal Lahir',
        'class' : 'form-control',
    }

    email_attrs = {
        'type': 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    password_attrs = {
        'type': 'password',
        'placeholder': 'Password',
        'class' : 'form-control'
    }

    nama = forms.CharField(label='Nama Lengkap', required=True, widget=forms.TextInput(attrs = nama_attrs))
    tanggal_lahir = forms.DateField(label='Tanggal Lahir', required=True, widget=forms.DateInput(attrs = tanggal_lahir_attrs))
    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    password = forms.CharField(required=True, widget = forms.PasswordInput(attrs = password_attrs))

class Form_Donasi(forms.Form):
    error_messages = {
        'required': 'Please type',
    }

    nama_program_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Program',
        'class' : 'form-control',
    }

    nama_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Lengkap',
        'class' : 'form-control',
    }

    email_attrs = {
        'type': 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    jumlah_attrs = {
        'type': 'number',
        'placeholder': 'Jumlah Donasi',
        'class' : 'form-control',
    }

    OPTION = [(x.title, x.title) for x in Program.objects.all()]
    OPTION2 = [(x.title, x.title) for x in Program.objects.all()]

    nama_program = forms.ChoiceField(label = 'Nama Program', choices = [(x.title, x.title) for x in Program.objects.all()])
    nama = forms.CharField(label='Nama Lengkap', required=True, widget=forms.TextInput(attrs = nama_attrs))
    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    jumlah = forms.IntegerField(required=True, widget = forms.NumberInput(attrs = jumlah_attrs))

crowdfunding/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from .forms import Form_Daftar, Form_Donasi
from .models import Model_Daftar, Model_Donasi, User_Data
from django.core import serializers
import json

response = {}

# Create your views here.

def daftar(request):
	response['form_daftar'] = Form_Daftar
	html = "formdaftar.html"
	response['errmsg'] = ''
	return render(request, html, response)

def savedata(request):
	form = Form_Daftar(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['nama'] = request.POST['nama']
		response['tanggal_lahir'] = request.POST['tanggal_lahir']
		response['email'] = request.POST['email']
		response['password'] = request.POST['password']
		project = Model_Daftar(nama = response['nama'], tanggal_lahir = response['tanggal_lahir'], email = response['email'], password = response['password'])
			
		data = Model_Daftar.objects.all().filter(email = response['email']).count()

		if data == 0:
			project.save()
			project = Model_Daftar.objects.all()
			response['project'] = project
			html = 'terdaftar.html'
			return render (request, html, response)
		else:
			response['errmsg'] = 'email sudah terdaftar'
			html = 'formdaftar.html'
			return render (request, html, response)
	else:
		response['form_daftar'] = Form_Daftar
		response['errmsg']='input tidak valid'
		html = "formdaftar.html"
		return render(request, html, response)

def donasi(request):
	response['form_donasi'] = Form_Donasi
	response['errmsg']=''
	html = "formdonasi.html"
	return render(request, html, response)

def savedatadonasi(request):
	form = Form_Donasi(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['nama_program'] = request.POST['nama_program']
		response['nama'] = request.POST['nama']
		response['email'] = request.POST['email']
		response['jumlah'] = request.POST['jumlah']
		project = Model_Donasi(nama_program = response['nama_program'], nama = response['nama'], email = response['email'], jumlah = response['jumlah'])
		project.save()
		project = Model_Donasi.objects.all()
		response['project'] = project
		html = 'history_page.html'
		response['msg']='sudah donasi'
		# ============== azhar's code ================== 		
		vs_id = request.user.id
		my_donation = User_Data(user_id=vs_id, user_program=response['nama_program'], user_money=response['jumlah'])
		my_donation.save()
 		 # ============== azhar's code ==================
		return render (request, html, response)
	else:
		response['form_donasi'] = Form_Donasi
		response['errmsg']='input tidak valid'
		html = "formdonasi.html"
		return render(request, html, response)

# ============== azhar's code ==================
def data_func(request):
	vs_id = request.user.id
	data = serializers.serialize("json", User_Data.objects.filter(user_id=vs_id))
	json_now = json.dumps(json.loads(data))
	return HttpResponse(data, content_type='application/json')
# ============== azhar's code ==================

crowdfunding/templates/formdaftar.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>FUNDEE</title>
  <link rel="stylesheet" type="text/css" href="{%static 'stylesheet.css' %}"/>
  <link rel="stylesheet" href="{% static 'cssregis.css' %}" type="text/css">
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    {% include "layout/navbar.html" %}
    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-12" id="first">
              <h1 class="text-center"><b>START DONATING!</b></h1>
              <h4 class="text-center">"Giving is better than receiving because giving starts the receiving process."<br>
                  - Jim Rohn</h4>
          </div>
      </div>
      <div class="row" style="margin-top: 3%; display: flex;">
          <div class="col-md-4"></div>
          <div class="col-md-4">
                  <div class="col-sm-12 align-self-center" id="out">
                      <div class="col-sm-12 align-self-center" id="in">
                          <a href="{% url 'social:begin' 'google-oauth2' %}"
                             style="text-transform:none; font-weight: bold; display: inline-flex;">
                              <div class="left">
                                  <img width="20px" alt="Google &quot;G&quot; Logo" id='google'
                                       src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
                              </div>
                              Login with Google
                          </a>
                          <br>
                      </div>
                  </div>
          </div>
          <div class="col-md-4"></div>
      </div>
  
  </div>

    <br><br><br><br><br>
    {% include "layout/footer.html" %}
</body>
</html>

crowdfunding/templates/formdonasi.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Sinar Perak</title>
  <link rel="stylesheet" type="text/css" href="{%static 'stylesheet.css' %}"/>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  {% include "layout/navbar.html" %}
<br>
<section>
  <div>
        <div style="width: 30%; margin: auto;" class = "jumbotron">
          <div class="row" style="background-color: #DBF2FF">
          <h1 style="font-family: niramit; text-align: center; font-size: 40px;">Donasi</h1>
          <br>
          </div>
          <br>
          <form id="form" method="POST" action="{% url 'crowdfunding:terdonasi' %}">
            {% csrf_token %}
            {{ form_donasi.as_p }}
            <input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">
            <p>{{errmsg}}</p>
          </form>
          <a href="/" class="btn btn-default">Kembali</a>
        </div>
    </div>

</section>
<br><br><br><br><br>
{% include "layout/footer.html" %}
</body>
    
</html>